"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { Building2, Check, KeyRound, LoaderCircle, Plus, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { assignAdminRolesAction, changeAdminPasswordAction, createAdminRoleAction, createAdminUserAction, loadAdminAccessAction, setAdminUserActiveAction } from "@/app/actions";
import type { AdminAccessDto } from "@/lib/api";
import type { Notify } from "../types";

export function AdminPage({ notify }: { notify: Notify }) {
  const query = useQuery({ queryKey: ["admin-access"], queryFn: loadAdminAccessAction, staleTime: 10_000 });
  const [tab, setTab] = useState<"users" | "roles" | "mapping">("users");
  if (query.isLoading) return <AdminState icon={<LoaderCircle className="spin"/>} title="Loading access control" detail="Reading users, roles, and organization mappings…"/>;
  if (query.isError || !query.data) return <AdminState icon={<ShieldCheck/>} title="Super admin access required" detail="This workspace is available only to an active super administrator." retry={() => query.refetch()}/>;
  const refresh = async (message: string) => { await query.refetch(); notify(message); };
  return <section className="admin-page"><div className="section-heading"><div><span className="section-kicker">Platform governance</span><h1>Super Admin</h1><p>Register users, create roles, and control organization access from one audited workspace.</p></div><button className="secondary-button" onClick={() => query.refetch()}><RefreshCw size={15}/>Refresh</button></div><div className="admin-summary"><span><Users size={19}/><b>{query.data.users.length}</b><small>Users</small></span><span><KeyRound size={19}/><b>{query.data.roles.length}</b><small>Roles</small></span><span><Building2 size={19}/><b>{query.data.organizations.length}</b><small>Organizations</small></span></div><nav className="admin-tabs"><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}><Users size={16}/>Users</button><button className={tab === "roles" ? "active" : ""} onClick={() => setTab("roles")}><KeyRound size={16}/>Roles & permissions</button><button className={tab === "mapping" ? "active" : ""} onClick={() => setTab("mapping")}><Building2 size={16}/>Organization mapping</button></nav>{tab === "users" && <UsersPanel data={query.data} refresh={refresh}/>} {tab === "roles" && <RolesPanel data={query.data} refresh={refresh}/>} {tab === "mapping" && <MappingPanel data={query.data} refresh={refresh}/>}</section>;
}

function UsersPanel({ data, refresh }: PanelProps) {
  const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await createAdminUserAction({ email: String(form.get("email")), fullName: String(form.get("fullName")), password: String(form.get("password")), superAdmin: form.get("superAdmin") === "on" }); event.currentTarget.reset(); await refresh("User registered"); } finally { setBusy(false); } };
  const changePassword = async (userId: string) => { const password = window.prompt("Enter a new password (minimum 10 characters)"); if (!password) return; await changeAdminPasswordAction(userId, password); await refresh("Password changed and existing sessions revoked"); };
  return <div className="admin-grid"><form className="panel admin-form" onSubmit={submit}><header><span><UserPlus size={19}/></span><div><h2>Register user</h2><p>The administrator sets the initial password.</p></div></header><label>Full name<input name="fullName" required maxLength={160}/></label><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={10} required/></label><label className="admin-check"><input name="superAdmin" type="checkbox"/>Grant super administrator access</label><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" size={15}/> : <Plus size={15}/>}Register user</button></form><div className="panel admin-list"><header><h2>Users</h2><p>Only administrators can change passwords or account status.</p></header>{data.users.map((user) => <article key={user.id}><span className="admin-avatar">{initials(user.full_name)}</span><div><b>{user.full_name}</b><small>{user.email}</small><em>{user.super_admin ? "Super Admin" : "User"}</em></div><button onClick={() => changePassword(user.id)}>Change password</button><button className={user.active ? "danger-text" : "success-text"} onClick={async () => { await setAdminUserActiveAction(user.id, !user.active); await refresh(user.active ? "User disabled" : "User enabled"); }}>{user.active ? "Disable" : "Enable"}</button></article>)}</div></div>;
}

function RolesPanel({ data, refresh }: PanelProps) {
  const [scope, setScope] = useState<"ORGANIZATION" | "PLATFORM">("ORGANIZATION"); const [selected, setSelected] = useState<string[]>([]); const available = data.permissions.filter((permission) => permission.scope === scope);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await createAdminRoleAction({ name: String(form.get("name")), description: String(form.get("description")), scope, permissions: selected }); event.currentTarget.reset(); setSelected([]); await refresh("Role created"); };
  return <div className="admin-grid"><form className="panel admin-form role-form" onSubmit={submit}><header><span><KeyRound size={19}/></span><div><h2>Create role</h2><p>Permissions are explicit; levels describe sensitivity.</p></div></header><label>Role name<input name="name" required/></label><label>Description<textarea name="description" rows={2}/></label><label>Scope<select value={scope} onChange={(event) => { setScope(event.target.value as typeof scope); setSelected([]); }}><option value="ORGANIZATION">Organization</option><option value="PLATFORM">Platform</option></select></label><div className="permission-picker">{[0,1,2].map((level) => <section key={level}><h3>Level {level}<small>{level === 0 ? "Standard" : level === 1 ? "Management" : "Sensitive"}</small></h3>{available.filter((permission) => permission.permission_level === level).map((permission) => <label key={permission.code}><input type="checkbox" checked={selected.includes(permission.code)} onChange={() => setSelected((current) => current.includes(permission.code) ? current.filter((code) => code !== permission.code) : [...current, permission.code])}/><span><b>{permission.description}</b><small>{permission.code}</small></span></label>)}</section>)}</div><button className="primary-button" disabled={!selected.length}><Plus size={15}/>Create role</button></form><div className="panel admin-list role-list"><header><h2>Available roles</h2><p>System roles are protected from modification.</p></header>{data.roles.map((role) => <article key={role.id}><span className="role-level">{Math.max(0, ...role.permissions.map((code) => data.permissions.find((item) => item.code === code)?.permission_level ?? 0))}</span><div><b>{role.name}</b><small>{role.description || "No description"}</small><em>{role.scope} · {role.permissions.length} permissions</em></div>{role.system_role && <i><ShieldCheck size={13}/>Protected</i>}</article>)}</div></div>;
}

function MappingPanel({ data, refresh }: PanelProps) {
  const [userId, setUserId] = useState(data.users[0]?.id ?? ""); const [organizationId, setOrganizationId] = useState(data.organizations[0]?.id ?? ""); const [scope, setScope] = useState<"ORGANIZATION" | "PLATFORM">("ORGANIZATION"); const [roleIds, setRoleIds] = useState<string[]>([]); const roles = useMemo(() => data.roles.filter((role) => role.scope === scope), [data.roles, scope]);
  const submit = async (event: FormEvent) => { event.preventDefault(); await assignAdminRolesAction({ userId, organizationId: scope === "ORGANIZATION" ? organizationId : undefined, roleIds }); await refresh(scope === "ORGANIZATION" ? "Organization access updated" : "Platform roles updated"); };
  return <div className="panel mapping-panel"><header><span><Building2 size={20}/></span><div><h2>Assign access</h2><p>Organization roles isolate tenant data. Platform roles control global capabilities such as organization creation.</p></div></header><form onSubmit={submit}><label>User<select value={userId} onChange={(event) => setUserId(event.target.value)}>{data.users.map((user) => <option key={user.id} value={user.id}>{user.full_name} · {user.email}</option>)}</select></label><label>Access scope<select value={scope} onChange={(event) => { setScope(event.target.value as typeof scope); setRoleIds([]); }}><option value="ORGANIZATION">Organization</option><option value="PLATFORM">Platform</option></select></label>{scope === "ORGANIZATION" && <label>Organization<select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{data.organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label>}<fieldset><legend>{scope === "ORGANIZATION" ? "Organization roles" : "Platform roles"}</legend>{roles.map((role) => <label key={role.id}><input type="checkbox" checked={roleIds.includes(role.id)} onChange={() => setRoleIds((current) => current.includes(role.id) ? current.filter((id) => id !== role.id) : [...current, role.id])}/><span><b>{role.name}</b><small>{role.permissions.length} permissions</small></span>{roleIds.includes(role.id) && <Check size={15}/>}</label>)}{roles.length === 0 && <p>Create a {scope.toLowerCase()} role before assigning it.</p>}</fieldset><button className="primary-button" disabled={!userId || (scope === "ORGANIZATION" && !organizationId) || !roleIds.length}><Check size={15}/>Save assignment</button></form></div>;
}

type PanelProps = { data: AdminAccessDto; refresh: (message: string) => Promise<void> };
function AdminState({ icon, title, detail, retry }: { icon: React.ReactNode; title: string; detail: string; retry?: () => void }) { return <div className="panel admin-state"><span>{icon}</span><h2>{title}</h2><p>{detail}</p>{retry && <button className="secondary-button" onClick={retry}><RefreshCw size={15}/>Retry</button>}</div>; }
function initials(name: string) { return name.split(/\s+/).slice(0,2).map((part) => part[0]).join("").toUpperCase(); }
