import { Activity, AlertCircle, Bot, Check, CheckCircle2, Code2, Files, Globe2, MessagesSquare, Network, RotateCcw } from "lucide-react";
import type { Agent, DashboardBackendData, Organization } from "../types";
import { PageHeading } from "../shared";

export function DashboardPage({ agents, organization, data }: { agents: Agent[]; organization: Organization; data: DashboardBackendData }) {
  const activeAgents = agents.filter((agent) => agent.status === "Live").length;
  const draftAgents = agents.filter((agent) => agent.status === "Draft").length;
  const totalDocuments = data.processing.completed + data.processing.processing + data.processing.failed;
  const activityIcon = (kind: DashboardBackendData["activity"][number]["kind"]) => kind === "document" ? <Code2 size={17}/> : kind === "widget" ? <Code2 size={17}/> : <Bot size={17}/>;

  return <>
    <PageHeading eyebrow="Organization" title={organization.name} description="Current configuration and processing status for this organization." />
    <div className="backend-summary-grid">
      <section className="panel backend-summary-card agents-summary"><div className="backend-card-head"><span><Bot size={20}/></span><div><h2>FAQ Agents</h2><p>Agents owned by {organization.name}</p></div></div><strong className="backend-total">{agents.length}</strong><span className="backend-total-label">Total agents</span><div className="backend-inline-stats"><span><i className="active"/><b>{activeAgents}</b> Active</span><span><i className="draft"/><b>{draftAgents}</b> Draft</span></div></section>
      <section className="panel backend-summary-card documents-summary"><div className="backend-card-head"><span><Files size={20}/></span><div><h2>Knowledge Documents</h2><p>Uploaded to FAQ agents</p></div></div><strong className="backend-total">{totalDocuments}</strong><span className="backend-total-label">Total documents</span><div className="backend-card-foot"><CheckCircle2 size={14}/>{data.processing.completed} ready for retrieval</div></section>
      <section className="panel backend-summary-card processing-summary"><div className="backend-card-head"><span><RotateCcw size={20}/></span><div><h2>Document Processing</h2><p>Current pipeline state</p></div></div><div className="processing-counts"><div><span className="processing-dot completed"><Check size={15}/></span><strong>{data.processing.completed}</strong><small>Completed</small></div><div><span className="processing-dot running"><RotateCcw size={15}/></span><strong>{data.processing.processing}</strong><small>Processing</small></div><div><span className="processing-dot failed"><AlertCircle size={15}/></span><strong>{data.processing.failed}</strong><small>Failed</small></div></div><div className="processing-bar">{totalDocuments > 0 && <><i className="completed" style={{width: `${data.processing.completed / totalDocuments * 100}%`}}/><i className="running" style={{width: `${data.processing.processing / totalDocuments * 100}%`}}/><i className="failed" style={{width: `${data.processing.failed / totalDocuments * 100}%`}}/></>}</div></section>
      <section className="panel backend-summary-card orchestrator-summary"><div className="backend-card-head"><span><Network size={20}/></span><div><h2>AI Orchestrator</h2><p>Organization routing configuration</p></div></div><div className="configuration-state"><span className={data.orchestratorConfigured ? "configured" : "unconfigured"}><i/>{data.orchestratorConfigured ? "Active" : "Not configured"}</span></div><div className="backend-detail-row"><span>Registered agents</span><b>{agents.length}</b></div></section>
      <section className="panel backend-summary-card widget-summary"><div className="backend-card-head"><span><MessagesSquare size={20}/></span><div><h2>Widgets</h2><p>Saved widget configurations</p></div></div><div className="widget-config-rows"><div><span><Globe2 size={16}/>Organization Widget</span><b className={data.organizationWidgetConfigured ? "configured" : "unconfigured"}>{data.organizationWidgetConfigured ? "Configured" : "Not configured"}</b></div><div><span><Bot size={16}/>FAQ Agent Widgets</span><b>{data.faqAgentWidgets}</b></div></div></section>
    </div>
    <section className="panel backend-activity-panel"><div className="panel-title"><div><h2>Recent Activity</h2><p>Changes recorded for {organization.name}</p></div><span className="activity-count">{data.activity.length} events</span></div>{data.activity.length ? <div className="backend-activity-list">{data.activity.map((event) => <div key={event.id}><span className={`activity-kind ${event.kind}`}>{activityIcon(event.kind)}</span><div><b>{event.label}</b><small>{event.context}</small></div><time>{event.time}</time></div>)}</div> : <div className="backend-activity-empty"><Activity size={20}/><span>No organization activity yet.</span></div>}</section>
  </>;
}
