"use client";

import { useState } from "react";
import { Bot, ChevronDown, ChevronRight, Copy, MessagesSquare, MoreHorizontal, Network, Plus, RotateCcw, Send, Sparkles, Zap } from "lucide-react";
import type { Notify } from "../types";
import { PageHeading } from "../shared";

type Props = { notify: Notify; embedded?: boolean; organizationMode?: boolean; agentName?: string; organizationName?: string; orchestratorName?: string };

export function PlaygroundPage({ notify, embedded = false, organizationMode = false, agentName = "Customer Support", organizationName = "Organization", orchestratorName }: Props) {
  const [mode, setMode] = useState<"Organization" | "FAQ Agent">(organizationMode ? "Organization" : "FAQ Agent");
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([{ role: "user", text: "What is your refund policy for annual plans?" }, { role: "assistant", text: "Annual plans are eligible for a full refund within 30 days of purchase. After that window, your plan remains active until the end of the billing period, but we can’t issue a prorated refund." }]);
  const send = () => {
    if (!message.trim()) return;
    setMessages((current) => [...current, { role: "user", text: message }, { role: "assistant", text: "Thanks for your question. Based on the connected knowledge, I’ve found the relevant information and can help you with that." }]);
    setMessage("");
  };

  return <>
    {!embedded && <PageHeading eyebrow="Safe testing space" title="AI Playground" description="Try questions, inspect routing, and refine answers before you publish."><button className="secondary-button" onClick={() => { setMessages([]); notify("New conversation started"); }}><RotateCcw size={15}/> New chat</button></PageHeading>}
    {embedded && <div className="section-intro"><div><h2>{organizationMode ? "Orchestrator playground" : `${agentName} playground`}</h2><p>{organizationMode ? "Test organization-wide routing and inspect the selected agent." : "Test this agent directly against its own knowledge."}</p></div><button className="secondary-button" onClick={() => { setMessages([]); notify("New conversation started"); }}><RotateCcw size={15}/> New chat</button></div>}
    <div className="playground-layout">
      <aside className="playground-settings panel"><div className="panel-title"><div><h2>Test settings</h2><p>Choose how to route this chat.</p></div></div>{!embedded && <><label className="field"><span>Playground mode</span></label><div className="segmented"><button onClick={() => setMode("Organization")} className={mode === "Organization" ? "selected" : ""}><Network size={15}/> Organization</button><button onClick={() => setMode("FAQ Agent")} className={mode === "FAQ Agent" ? "selected" : ""}><Bot size={15}/> Direct agent</button></div></>}<label className="field"><span>{mode === "Organization" ? "Orchestrator" : "Current agent"}</span><button className="select-field"><span className="mini-agent"><Sparkles size={14}/></span>{mode === "Organization" ? orchestratorName || `${organizationName} Assistant` : agentName}{!embedded && <ChevronDown size={15}/>}</button></label><div className="info-card"><Zap size={16}/><div><b>Test details</b><p>The selected agent and retrieved sources are visible after each test response.</p></div></div><div className="settings-footer"><span><i/> Knowledge ready</span><small>Available for testing</small></div></aside>
      <section className="chat-panel panel"><div className="chat-header"><div className="chat-agent"><span><Sparkles size={18}/></span><div><b>{mode === "Organization" ? orchestratorName || `${organizationName} Assistant` : agentName}</b><small><i/> Online · {mode === "Organization" ? "Orchestrator" : "Direct agent"} mode</small></div></div><button className="icon-button small"><MoreHorizontal size={17}/></button></div><div className="messages"><div className="chat-date"><span>Today</span></div>{messages.length === 0 && <div className="empty-chat"><span><MessagesSquare size={26}/></span><h3>Start a new conversation</h3><p>Ask a question your customers might ask.</p></div>}{messages.map((item, index) => item.role === "user" ? <div className="message user-message" key={index}><div>{item.text}</div><span className="tiny-avatar">OS</span></div> : <div className="message assistant-message" key={index}><span className="bot-avatar"><Sparkles size={15}/></span><div className="answer-wrap"><div className="answer-bubble"><p>{item.text}</p><p>Would you like me to explain how to request one?</p></div><div className="answer-meta"><span><Bot size={12}/> Answered by <b>{mode === "Organization" ? "selected FAQ agent" : agentName}</b></span><button onClick={() => notify("Response copied")}><Copy size={12}/></button><button><RotateCcw size={12}/></button></div><button className="routing-details"><ChevronRight size={13}/> View routing & sources</button></div></div>)}</div><div className="composer"><div className="suggestions"><button onClick={() => setMessage("How do I upgrade my plan?")}>How do I upgrade my plan?</button><button onClick={() => setMessage("Where can I find my invoices?")}>Where are my invoices?</button></div><div className="composer-box"><textarea value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }} placeholder="Ask your agent a question..." rows={2}/><div><button className="attach-button"><Plus size={17}/></button><span>Enter to send</span><button className="send-button" onClick={send}><Send size={17}/></button></div></div><small>AI can make mistakes. Verify important information.</small></div></section>
    </div>
  </>;
}
