import { Building2, KeyRound, Mail, ShieldCheck, UserRound } from "lucide-react";
import type { CurrentUserDto } from "@/lib/api";

export function ProfilePage({ user }: { user: CurrentUserDto }) {
  const organizationCount = Object.keys(user.organization_permissions).length;
  return <section className="profile-page"><div className="section-heading"><div><span className="section-kicker">Personal account</span><h1>Profile & access</h1><p>Your identity and the workspace access assigned by an administrator.</p></div></div><div className="profile-layout"><article className="panel profile-identity-card"><span className="profile-hero-avatar">{initials(user.full_name)}</span><h2>{user.full_name}</h2><p>{user.email}</p><em><ShieldCheck size={14}/>{user.super_admin ? "Super administrator" : "Organization user"}</em><div><span><UserRound size={17}/><small>Account status</small><b>{user.active ? "Active" : "Disabled"}</b></span><span><Mail size={17}/><small>Login identity</small><b>{user.email}</b></span><span><Building2 size={17}/><small>Organizations</small><b>{user.super_admin ? "Platform-wide administration" : `${organizationCount} mapped`}</b></span></div></article><article className="panel profile-access-card"><header><span><KeyRound size={19}/></span><div><h2>Access policy</h2><p>Passwords and role assignments are managed by a super administrator.</p></div></header><div className="profile-access-note"><ShieldCheck size={18}/><span><b>Secure account controls</b><p>Contact your administrator when your name, password, organization mapping, or permissions need to change.</p></span></div><h3>Organization access</h3>{user.super_admin ? <p className="profile-platform-access">You can administer users, roles, permissions, and organization mappings from the Super Admin workspace.</p> : <div className="profile-org-access">{Object.entries(user.organization_permissions).map(([organizationId, permissions]) => <span key={organizationId}><Building2 size={16}/><b>{organizationId}</b><small>{permissions.length} effective permissions</small></span>)}{organizationCount === 0 && <p>No organization has been mapped to this account.</p>}</div>}</article></div></section>;
}

function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "U"; }
