"use client";

import { useState } from "react";
import { Bot, CheckCircle2, Clipboard, Globe2, MessagesSquare, Network, Send, Sparkles, X } from "lucide-react";
import type { Notify } from "../types";
import { PageHeading } from "../shared";

type Props = { notify: Notify; embedded?: boolean; agentMode?: boolean; agentName?: string };

export function WidgetsPage({ notify, embedded = false, agentMode = false, agentName = "Customer Support" }: Props) {
  const [widgetType, setWidgetType] = useState<"Organization" | "Agent">(agentMode ? "Agent" : "Organization");
  const [open, setOpen] = useState(true);
  const snippet = agentMode ? '<script src="https://cdn.arffy.ai/widget.js" data-agent="agent_cs_8f21"></script>' : '<script src="https://cdn.arffy.ai/widget.js" data-organization="acme_92a7"></script>';
  return <>
    {!embedded && <PageHeading eyebrow="Publish with confidence" title="Widget deployment" description="Customize your assistant, preview it live, then add it to any website."><button className="primary-button" onClick={() => notify("Widget configuration published")}><Globe2 size={16}/> Publish changes</button></PageHeading>}
    {embedded && <div className="section-intro"><div><h2>{agentMode ? `${agentName} widget` : "Organization widget"}</h2><p>{agentMode ? `Deploy a widget that sends every question directly to ${agentName}.` : "Deploy your public assistant and route questions through the AI Orchestrator."}</p></div><button className="primary-button" onClick={() => notify("Widget configuration published")}><Globe2 size={16}/> Publish changes</button></div>}
    <div className="widget-layout">
      <section className="panel widget-config"><div className="panel-title"><div><h2>Configure widget</h2><p>Changes appear in the preview instantly.</p></div></div>{!embedded && <><label className="field"><span>Widget type</span></label><div className="widget-type-grid"><button className={widgetType === "Organization" ? "selected" : ""} onClick={() => setWidgetType("Organization")}><Network size={20}/><b>Organization</b><small>Route to the best agent</small><CheckCircle2 size={17}/></button><button className={widgetType === "Agent" ? "selected" : ""} onClick={() => setWidgetType("Agent")}><Bot size={20}/><b>Direct agent</b><small>Use one specific agent</small><CheckCircle2 size={17}/></button></div><div className="form-divider"/></>}<label className="field"><span>Assistant name</span><input defaultValue={agentMode ? agentName : "Acme Assistant"}/></label><label className="field"><span>Welcome message</span><textarea rows={3} defaultValue="Hi there! 👋 How can we help today?"/></label><div className="field"><span>Brand color</span><div className="color-options"><button className="selected" style={{background:"#168c86"}}/><button style={{background:"#2563eb"}}/><button style={{background:"#0f9f73"}}/><button style={{background:"#e45858"}}/><button style={{background:"#171923"}}/></div></div></section>
      <section className="panel preview-panel"><div className="preview-toolbar"><div><h2>Live preview</h2><span>Desktop</span></div><div><button>Desktop</button><button>Mobile</button></div></div><div className="browser-frame"><div className="browser-bar"><i/><i/><i/><span>yourwebsite.com</span></div><div className="fake-site"><header><b>ACME</b><span>Product&nbsp;&nbsp;&nbsp; Solutions&nbsp;&nbsp;&nbsp; Pricing</span><button>Get started</button></header><main><span>AI-POWERED SUPPORT</span><h3>Support that never<br/>keeps you waiting.</h3><p>Give your customers instant, accurate answers—day or night.</p><button>Start free trial</button></main>{open ? <div className="widget-chat"><div className="widget-chat-head"><span><Sparkles size={16}/></span><div><b>{agentMode ? agentName : "Acme Assistant"}</b><small><i/> Online</small></div><button onClick={() => setOpen(false)}><X size={15}/></button></div><div className="widget-chat-body"><div className="widget-bubble">Hi there! 👋 How can we help today?</div><div className="widget-time">Just now</div><div className="widget-suggestions"><button>Track my order</button><button>View pricing</button></div></div><div className="widget-input"><span>Type a message...</span><Send size={15}/></div></div> : <button className="widget-launcher" onClick={() => setOpen(true)}><MessagesSquare size={22}/><i/></button>}</div></div></section>
    </div>
    <section className="panel install-panel"><div className="panel-title"><div><h2>Install on your website</h2><p>Paste this snippet before the closing &lt;/body&gt; tag.</p></div><span className="secure-badge"><CheckCircle2 size={13}/> Ready to install</span></div><div className="code-block"><code>{snippet}</code><button onClick={() => { navigator.clipboard?.writeText(snippet); notify("Embed code copied"); }}><Clipboard size={15}/> Copy code</button></div></section>
  </>;
}
